### ISSUE TITLE
Can't access localhost:8888

### ISSUE THREAD

**Issue by zachary** [innopearl/docker-compose-zipline#1]
zipline-jupyter | [W 00:02:21.456 NotebookApp] SSL Error on 9 ('172.19.0.1', 34032): [SSL: HTTP_REQUEST] http request (_ssl.c:847)

always get this error from docker logs

thanks

**Comment by innopearl** [comment]
in your system, 8888 has been occupied by some other (web) service as that port is something common. You can try to launch it on another free port, e.g. 8889 by replacing line 10 of docker-compose.yml
from
- "8888:8888" 
into 
- "8889:8888"
